---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        name: Run yamllint
        description: Lint yaml files
        entry: yamllint -c .github/.yamllint-config.yaml
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.0
    hooks:
      - id: markdownlint
        name: Run markdownlint
        description: Lint markdown files
        entry: markdownlint -c .github/.markdownlint.yaml
  - repo: local
    hooks:
      - id: check-sops-secrets
        name: Check for unencrypted SOPS secrets
        entry: ./hack/check-sops-secrets-hook.sh
        language: script
        files: \.(ya?ml)$
