fail_fast: false
repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.7.0
  hooks:
  - id: pretty-format-java
    args: [--autofix]
  - id: pretty-format-kotlin
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.19
  hooks:
  - id: terraform-fmt
- repo: https://github.com/yuvipanda/pre-commit-hook-ensure-sops
  rev: v1.0
  hooks:
  - id: sops-encryption
