kind: ENC[AES256_GCM,data:5YaLLu3P,iv:P8s8zXJuHclwBWrX7WZO4hyrRWyT4NgFuOVpwFkx55A=,tag:8jWx1deITo3y/ClyeOlO7w==,type:str]
ansible_user: ENC[AES256_GCM,data:kTok6OgvTKG4,iv:3P2t5uCONKAvBKsaL1m4pJ2QM2wQOqrWQd34HiYm310=,tag:wz0JeBt99ThaidxV0qy78g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:VlYw1QFymMu4B++i728=,iv:4RRbuG/lW6gUif+bhsd63ntgx0L1EO6bIpC4BRz+HWA=,tag:zLesuD5+TSlyEyFhj9I2qQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e4clsp6eptarnqjvkyyjatqvepk9jfe7q7klldsjtkcfjt0naqjqy8tdsx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUDcwRGRwdGtHNGlBWUFk
            WXQxMTBKV2JqaUljSVJOVHZEOVJ6dUREbkNRCnluMmpibit1a0tLUzF0UkFJeVAr
            Vk85aWhwK0RsaFg1VDdPcng0TW5yNjQKLS0tIDlLKzdPTUVtLzRXS2RTUDlGV1hZ
            ekVwWlFLRXlpc2JrUnpQUXYyTmFqd1EKcM/OouyHGJYVM8DQia7I88q46ulSz5/7
            TFtM54A1yVbUeoitkDWZuGCXYmAnH5GdeQ493Vy33nmiHfkcXlEZmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T23:10:40Z"
    mac: ENC[AES256_GCM,data:xY08JaV6xsLE0dbojMGiHs/QQxrNGQfTxxd1M9ucBR40S95HjhhLtkIk1qK+hHM7XPM/Oexyj6AEfSUvAI0ZEB8E6FlKBltIMIpJ6k2s9sKDfBQ4xYvroUPMSdcEidgKLgz23M3nuehHLddF27wjx3iXYLy1Pn9KtqXd+1/SV7I=,iv:yrqkOmN+4XvY+jJBMDhpTWyCVKpGzhSzp7PwolXZpuo=,tag:D7whl+1mJE8H8kw8d21twQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
