apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:uAbI2V86LrFe3iofvElKwCkBKBMBKD1WzhMb7qKnzA==,iv:LlgvyzQO37U5qVD5cmfGpqVme9jyhR1dGfF0YYNY3/E=,tag:pVzxaSfttoTql/2bz+yS0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e4clsp6eptarnqjvkyyjatqvepk9jfe7q7klldsjtkcfjt0naqjqy8tdsx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTDRTNWh5dzhaRnh1T3JP
            SXM4Z2JRd1lzVUdCYjdMQjFtR2ErMmViMlVBCkdhaEpsMi9sK3FoM2QxekJuTEp0
            Z2FMS1FtVWpvOHlzTjlKWEU3ci9qa1EKLS0tIElZdUp5V0Q0eWk3L3VhOUxMd1U0
            S2xYckVGK0tORy9ROWtiNCtkb2FaeFEKvV/xjgDNGni9wCXIuWhfRyUwxQdHXPaP
            y2dXe4WmNpLzZvavwXklJ1GKLRkTXRMKkDJxEH5ZGJiS7/kMRT26sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T23:10:40Z"
    mac: ENC[AES256_GCM,data:jjn3Hm1RYpi1yHfb3T9tkX5fhoJ+T4vaFr9Oor+SBmUE4YdhKFo/gvrd+5Kg8u1IauzIIbJEeh6x9E1BX3GAAirtRSqBd5UtaeCnZcloembR1dJuciHN6asOI5S2qIoSQ2IeTIwtnJQc9VBgvJBdmz+NaVs++3hdEvQ44YEkuRw=,iv:3x19le8YpwpRJ4fSnKBd6sD/YuQbv0gA6pMuGS+DLk4=,tag:yziaNAh1/tfGoMmQq3EE4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
