apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ELTq3rVSLDco5j10fxFy9iyaBNaA6iecgZPjD5B6YMA7kBIX0Q==,iv:1BbBnNjHlU7U//z/7PIfxTXz6WFmvLa8KFP6+vy34rk=,tag:sUuIgfW4KWO6GW4a1zZTUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e4clsp6eptarnqjvkyyjatqvepk9jfe7q7klldsjtkcfjt0naqjqy8tdsx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWklpWGhsN3Yya0N2ZXN0
            UDI4Ky9vVEw0T2Nqa0xzb3pwV2Z5WklSeWxnCnJjeXlBdnVHM056a3pmbWZlOHN2
            bmNrNXJyT3lPMmNHWEpXQlcvOHkrc0UKLS0tIFkxdXp1UTh2TnJpY3UrZm1kMHkz
            a2R5T0FXVWNiQXdMeUdIRHFTSlc3SlUKBYNN0dmekkg7Weyt4hITtrrtUeDfBk7h
            2qg5EafgF3GFkO6dlxHX3QQnwtFAsx2RQNZUxUOdRpVmIGLxMfe7SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T23:10:40Z"
    mac: ENC[AES256_GCM,data:acB52sD9c4nAuYapz3Po6iDQ7SkbkGI7T/N4WiukMn3uHEvvjp2X9zeRhb8oMmtefRyTUQor0FEsT1j2Z5lkLRlrraaJiOAZYKFbtMGzNt7x9Xtz+MBxjR3ArhNldPCprFYf8/5745cMfeKNwgUFG+mHaE7lPq3xe9YOXHiXlE4=,iv:e3r/rQmdqeV4v6fwzJDlMZFYQtaTE/I/966jE9CQQZg=,tag:gNjjVNwfHaNJk80vX4fkWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
