apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:5mpkOYhBud6h8t2m7KV3R5k=,iv:qDqtTA7tEs5fOkAVpy1n7yQSoAZG83JAxn9teNvKCC8=,tag:YPO4DZ8vnypTRg9EKZU9Kw==,type:str]
    api-key: ENC[AES256_GCM,data:O1aEp0UxjPySG2u7I+r/8nXNVJhSMiavWDZ5RZ2ChL6xtFuMEw==,iv:WIh2BuISkQln9u32p4x+mgjBzuu7GEqyDjK9CooEgQk=,tag:q74Eu/sMv4YVoLIlpg/Q5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e4clsp6eptarnqjvkyyjatqvepk9jfe7q7klldsjtkcfjt0naqjqy8tdsx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQkJDS2tmQXlkUzJmQzcr
            MXJtTlMxV0pOV1hTcmEyc0dPQUNJaktvekdZClBvTmNCay85TU80N3VYRkhXaTg2
            cU9MdWx2ZmJodllZMzBWa2dLV1B1cE0KLS0tIDJRRjlRUzBhL1NYM0x3SkhxSUpw
            SWRGakRseitKNTJRMmxGL0gxYjQzaFUKX+DJJ2gS4x1hIJvV5mZaYWrRfma0vw19
            r4SHwifCYtMBwPHa3pqpXDq2KYI7ithZHta9b2Ut8zNkfxbDCmNthA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T23:10:40Z"
    mac: ENC[AES256_GCM,data:ugTpDgBofmHB1I7+FWp8PZVL6IJ9QrJwy2PgH55+qa3Y0H1ExBlkTWn1BOsWdmYXy25ViCu2sE5emaM8cR71lgwzuqndkb2eFkVJkj7XZhnu/MBKKU6cLpR2UYiPObaFhAyWXWMEsLE+bW6lzS+rvPxqLMiHtE1xgH1Z2ETH+2M=,iv:+fDOAkJAAuKZ6lH+0gIWPTKiBwi6ivbt8RtIiPEfSDQ=,tag:xihinIfKOirpHgRayKMZ8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
