apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:Zs4dXeygYZa5gGOtp3u/JKHep5O7cBrHuBrlwgWpzG4qopAhhSnXPaEbYj6wdZ5fg6Lct1Zs1Vig/7/Q,iv:edW//oGFpbPYOc4UCPmvVmX14RgxjoF5fZv66MTcf7o=,tag:XhqNkh+u5gZfpAKPzErtJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e4clsp6eptarnqjvkyyjatqvepk9jfe7q7klldsjtkcfjt0naqjqy8tdsx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZHpRenRFbTdlSlg3VzBq
            RXNaUUFmSXFQUEMvbkdHYUFpSFdBQTYyL0NrCmlSK0ZqOVh5MFVpZitjSlMrNlJx
            U0NON29SaStiT0JzOHB0b3A2NzJlNWsKLS0tIEhoTGh5U0ZZdGdjRzBjMEE0dDBM
            czVuc0J3QzRVTXlXamt6SFo4b0x2b1EK9MDv7IVWHP+EiF9i0NCSzuaGXpsnJGVV
            DF6fYWXqMCW+BhRawYeyl4WWuAR5MWdyz9Nc/bM1AI1eqK7AkLJsDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T23:10:40Z"
    mac: ENC[AES256_GCM,data:iYv7PAIB8izMPF17VRPo9nb/N+LGocpXYzbbZPq2pG9yQT6pqCPr64eudOktIMastaLq2Bhf6N/YlRCNdbYEnNFy5mkBpqnrRvNCNJpsXCv8kAfw50ldDQBHdDRxRkP7IIlOFaweNYLx4zYWvTyTXSV8WIVsTPWRLB4kwFUp1Lg=,iv:PUCR0KmuG8DkJzBKe5h1XrV68Esmd+ZoZwzivx/7zzc=,tag:JusKSIJXEaMccl/EM3bK5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
