---
# yaml-language-server: $schema=https://kubernetes-schemas.int.glencook.tech/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lidarr-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # LIDARR__API_KEY
        key: lidarr
